paths:
  /api/products:
    get:
      summary: Obtener a todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Usuarios obtenidos correctamente
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      parameters:
        - name: body 
          in: body
          required: true
          schema:
            type: object
            properties:
              first_name: 
                type: string
              last_name: 
                type: string
              email: 
                type: string
              password: 
                type: string  
      responses:
        '201':
          description: Usuario creado correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
  /api/products/{id}:  
    get:
      summary: Obtener un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: ID del usuario a buscar
      responses:
        '200':
          description: Usuario obtenido correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar un usuario
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: ID del producto a actualizar
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              title: 
                type: string
              description: 
                type: string
              stock: 
                type: Number
              status: 
                type: string
              code: 
                type: string
              price: 
                type: Number
              category: 
                type: string
      responses:
        '200':
          description: producto actualizado correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar un usuario
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: ID del usuario a eliminar
      responses:
        '200':
          description: Usuario Eliminado correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Error interno del servidor
components:
  schemas:
    Product: 
      type: object
      properties:
        _id: 
          type: 0bjectId
          description: ID autogenerado por MongoDb
        title: 
          type: String
          description: Nombre del producto
        description: 
          type: String
          description: descripsion del producto
        price: 
          type: Number
          description: Precio del producto
        stock: 
          type: Number
          description: Stock del producto
        category:
          type: String
          description: Categoria del producto
        status:
          type: Boolean
          description: Status del producto
        code:
          type: String
          description: Codigo del producto
      example:
        _id: "61b214bb3f4c9b6dffdeebeb"
        title: "Cafetera Eléctrica"
        description: "Cafetera eléctrica con capacidad para 12 tazas."
        price: 49.99
        stock: 100
        category: "Electrodomésticos"
        status: true
        code: "CAF1234ELEC"